---
- name: 设置服务器环境
  block:
    # - name: 临时设置主机名
    #   shell: hostnamectl set-hostname {{hostname|quote}}
      
    # - name: 修改hostname文件
    #   raw:  "echo {{hostname|quote}} > /etc/hostname"

    - name: 备份 /etc/hosts
      copy:
        remote_src: true
        src: /etc/hosts
        dest: /etc/hosts.backup
        force: no

    - name: 下发主机与IP映射
      blockinfile:
        backup: yes
        path: /etc/hosts
        block: |
          {{hosts_content}}        

    - name: 修改最大虚拟内存
      blockinfile:
        path: /etc/sysctl.conf
        block: |
          vm.max_map_count=655360
          net.ipv4.ip_forward = 1

    - name: 更新 /etc/sysctl.conf
      shell: "{{ item }}" 
      with_items:
        - sysctl -p
      ignore_errors: yes  

    - name: 修改最大文件打开数
      blockinfile:
        path: /etc/security/limits.conf
        block: |
          * soft nofile 65536
          * hard nofile 131072
          * soft nproc 2048
          * hard nproc 4096

    - name: 修改最大线程数
      replace:
        path: /etc/security/limits.d/20-nproc.conf
        regexp: "^(.*)          soft    nproc     1024"
        replace: "*          soft    nproc     2048" 
      ignore_errors: yes  

    - name: 关闭Swap
      shell: "{{ item }}" 
      with_items:
        - swapoff -a 
        - sysctl -w vm.swappiness=0
      ignore_errors: yes

    - name: 临时禁用SELinux
      shell: "setenforce 0"
      failed_when: false

    - name: 永久禁用SELinux
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=enforcing'
        replace: 'SELINUX=disabled'

    - name: 关闭防火墙
      service:
        name: firewalld
        state: stopped
        enabled: no

  when: ansible_system=="Linux" and ansible_distribution=="CentOS" and ansible_distribution_major_version=="7"
   