---
- name: 检查是否已经安装docker
  shell: 'systemctl is-active docker'
  register: docker_svc
  ignore_errors: yes

- name: 安装Docker
  block: 
    - name: 下载Docker
      get_url:
        url: https://mirrors.cloud.tencent.com/docker-ce/linux/static/stable/x86_64/docker-19.03.9.tgz
        dest: /tmp 
    - name: 解压Docker
      unarchive:
        src: "/tmp/docker-19.03.9.tgz"
        dest: /tmp         
    
    - name: 移动Docker文件
      copy:
        remote_src: true
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: '/tmp/docker/',dest: '/usr/local/bin/' }

    - name: 删除临时文件
      file:  
        path: /tmp/docker
        state: absent

    - name: 添加执行权限
      shell: chmod +x /usr/local/bin/*

    - name: 创建配置文件夹
      file:
        path: /etc/docker
        state: directory
    
    - name: 下发配置文件
      template: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: 'daemon.json.j2',dest: '/etc/docker/daemon.json' }
        - { src: 'docker.service.j2',dest: '/usr/lib/systemd/system/docker.service' }
         
    - name: 开机启动Docker
      systemd: 
        name: docker
        state: started
        enabled: true
        daemon-reload: true
      ignore_errors: yes

    - name: 等待Docker成功启动
      shell: "systemctl is-active docker.service"
      register: docker_status
      until: '"active" in docker_status.stdout'
      retries: 8
      delay: 5
  when: ('inactive' in docker_svc.stdout) or ('unknown' in docker_svc.stdout)